version: '3'
services:
    jupyter:
      env_file:
        - .env
      logging:
        options:
          max-size: $LOGSIZE  
      volumes:
        - ${LOCAL_WORKING_DIR}:/home/jovyan/work
        - ${LOCAL_DATASETS}:/home/jovyan/work/data
      build: .
      deploy:
        resources:
          limits:
            cpus: "0.90"
            memory: "12000M"
          reservations:
            cpus: "0.10"
            memory: "1024M"
      container_name: spark_sandbox
      #image: jupyter/minimal-notebook # always get `latest` image on docker hub
      ports:
        - ${NOTEBOOK_PORT}:${NOTEBOOK_PORT}
        - ${GUI_PORT}:${GUI_PORT}
      restart: unless-stopped
      environment:
          PASSWORD: '123456789'
          NB_UID: 1000
          JUPYTER_ENABLE_LAB: 'yes'
          GRANT_SUDO: 'yes'
          SPARK_MASTER_URL: spark://spark:7777
      command: >
          sh -c "bash start-notebook.sh\
                --NotebookApp.token=$ACCESS_TOKEN \
                --NotebookApp.notebook_dir=/home/jovyan/work/ \
                --NotebookApp.port=$NOTEBOOK_PORT"